name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
        #  context: ./src
          file: ./src/HabitsApp.WebAPI/Dockerfile
          push: true
          tags: frkndnz/habits-backend:latest
      - name: Update Azure Container App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az containerapp update \
              --name habits-backend \
              --resource-group MyApp \
              --image frkndnz/habits-backend:latest
            
          
           
