name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/HabitsApp.WebAPI/Dockerfile
          push: true
          tags: frkndnz/habits-backend:latest
      - name: Update Azure Container App
        uses: azure/cli@v1 # Azure CLI komutlarını çalıştırmak için bir GitHub Action kullanır
        with:
          inlineScript: |
            # Bu satırlar Azure'a kimlik doğrulaması yapmak içindir, eğer daha önce yapmadıysanız
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            # Container App'inizi yeni imajı kullanacak şekilde güncelleme komutu
            az containerapp update \
              --name habits-backend \ # Kendi Container App adınızı buraya yazın
              --resource-group MyApp \ # Kendi Kaynak Grubunuzu buraya yazın
              --image frkndnz/habits-backend:latest # Burası önemlidir: latest tag'ini tekrar belirtiyoruz
